spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:h2:file:${user.home}/person-db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    sql: debug